// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyMessage.proto

package top.zhaohaoren.netty.netty.protobuf;

public final class MyMessageProto {
  private MyMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *属性1：标识传入的是哪一个枚举类型
     * </pre>
     *
     * <code>.MyMessage.DataType data_type = 1;</code>
     */
    int getDataTypeValue();
    /**
     * <pre>
     *属性1：标识传入的是哪一个枚举类型
     * </pre>
     *
     * <code>.MyMessage.DataType data_type = 1;</code>
     */
    top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType getDataType();

    /**
     * <code>.Apple apple = 2;</code>
     */
    boolean hasApple();
    /**
     * <code>.Apple apple = 2;</code>
     */
    top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple getApple();
    /**
     * <code>.Apple apple = 2;</code>
     */
    top.zhaohaoren.netty.netty.protobuf.MyMessageProto.AppleOrBuilder getAppleOrBuilder();

    /**
     * <code>.Pear pear = 3;</code>
     */
    boolean hasPear();
    /**
     * <code>.Pear pear = 3;</code>
     */
    top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear getPear();
    /**
     * <code>.Pear pear = 3;</code>
     */
    top.zhaohaoren.netty.netty.protobuf.MyMessageProto.PearOrBuilder getPearOrBuilder();

    public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataBodyCase getDataBodyCase();
  }
  /**
   * <pre>
   * 定义一个message，通过该message选取我们要的类型
   * </pre>
   *
   * Protobuf type {@code MyMessage}
   */
  public  static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      dataType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_MyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.class, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.Builder.class);
    }

    /**
     * <pre>
     * 定义一个枚举
     * </pre>
     *
     * Protobuf enum {@code MyMessage.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *protoBuf枚举需要从0开始
       * </pre>
       *
       * <code>AppleType = 0;</code>
       */
      AppleType(0),
      /**
       * <code>PearType = 1;</code>
       */
      PearType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *protoBuf枚举需要从0开始
       * </pre>
       *
       * <code>AppleType = 0;</code>
       */
      public static final int AppleType_VALUE = 0;
      /**
       * <code>PearType = 1;</code>
       */
      public static final int PearType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return AppleType;
          case 1: return PearType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MyMessage.DataType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      APPLE(2),
      PEAR(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return APPLE;
          case 3: return PEAR;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     *属性1：标识传入的是哪一个枚举类型
     * </pre>
     *
     * <code>.MyMessage.DataType data_type = 1;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     *属性1：标识传入的是哪一个枚举类型
     * </pre>
     *
     * <code>.MyMessage.DataType data_type = 1;</code>
     */
    public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType getDataType() {
      @SuppressWarnings("deprecation")
      top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType result = top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType.valueOf(dataType_);
      return result == null ? top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType.UNRECOGNIZED : result;
    }

    public static final int APPLE_FIELD_NUMBER = 2;
    /**
     * <code>.Apple apple = 2;</code>
     */
    public boolean hasApple() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.Apple apple = 2;</code>
     */
    public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple getApple() {
      if (dataBodyCase_ == 2) {
         return (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) dataBody_;
      }
      return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.getDefaultInstance();
    }
    /**
     * <code>.Apple apple = 2;</code>
     */
    public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.AppleOrBuilder getAppleOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) dataBody_;
      }
      return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.getDefaultInstance();
    }

    public static final int PEAR_FIELD_NUMBER = 3;
    /**
     * <code>.Pear pear = 3;</code>
     */
    public boolean hasPear() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.Pear pear = 3;</code>
     */
    public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear getPear() {
      if (dataBodyCase_ == 3) {
         return (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) dataBody_;
      }
      return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.getDefaultInstance();
    }
    /**
     * <code>.Pear pear = 3;</code>
     */
    public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.PearOrBuilder getPearOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) dataBody_;
      }
      return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType.AppleType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType.AppleType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage)) {
        return super.equals(obj);
      }
      top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage other = (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage) obj;

      boolean result = true;
      result = result && dataType_ == other.dataType_;
      result = result && getDataBodyCase().equals(
          other.getDataBodyCase());
      if (!result) return false;
      switch (dataBodyCase_) {
        case 2:
          result = result && getApple()
              .equals(other.getApple());
          break;
        case 3:
          result = result && getPear()
              .equals(other.getPear());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + APPLE_FIELD_NUMBER;
          hash = (53 * hash) + getApple().hashCode();
          break;
        case 3:
          hash = (37 * hash) + PEAR_FIELD_NUMBER;
          hash = (53 * hash) + getPear().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义一个message，通过该message选取我们要的类型
     * </pre>
     *
     * Protobuf type {@code MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MyMessage)
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_MyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.class, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.Builder.class);
      }

      // Construct using top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_MyMessage_descriptor;
      }

      @java.lang.Override
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage getDefaultInstanceForType() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage build() {
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage buildPartial() {
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage result = new top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (appleBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = appleBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (pearBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = pearBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage) {
          return mergeFrom((top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage other) {
        if (other == top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case APPLE: {
            mergeApple(other.getApple());
            break;
          }
          case PEAR: {
            mergePear(other.getPear());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <pre>
       *属性1：标识传入的是哪一个枚举类型
       * </pre>
       *
       * <code>.MyMessage.DataType data_type = 1;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       *属性1：标识传入的是哪一个枚举类型
       * </pre>
       *
       * <code>.MyMessage.DataType data_type = 1;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *属性1：标识传入的是哪一个枚举类型
       * </pre>
       *
       * <code>.MyMessage.DataType data_type = 1;</code>
       */
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType getDataType() {
        @SuppressWarnings("deprecation")
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType result = top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType.valueOf(dataType_);
        return result == null ? top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *属性1：标识传入的是哪一个枚举类型
       * </pre>
       *
       * <code>.MyMessage.DataType data_type = 1;</code>
       */
      public Builder setDataType(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *属性1：标识传入的是哪一个枚举类型
       * </pre>
       *
       * <code>.MyMessage.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.Builder, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.AppleOrBuilder> appleBuilder_;
      /**
       * <code>.Apple apple = 2;</code>
       */
      public boolean hasApple() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple getApple() {
        if (appleBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) dataBody_;
          }
          return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return appleBuilder_.getMessage();
          }
          return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.getDefaultInstance();
        }
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public Builder setApple(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple value) {
        if (appleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          appleBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public Builder setApple(
          top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.Builder builderForValue) {
        if (appleBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          appleBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public Builder mergeApple(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple value) {
        if (appleBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.getDefaultInstance()) {
            dataBody_ = top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.newBuilder((top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            appleBuilder_.mergeFrom(value);
          }
          appleBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public Builder clearApple() {
        if (appleBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          appleBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.Builder getAppleBuilder() {
        return getAppleFieldBuilder().getBuilder();
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.AppleOrBuilder getAppleOrBuilder() {
        if ((dataBodyCase_ == 2) && (appleBuilder_ != null)) {
          return appleBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) dataBody_;
          }
          return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.getDefaultInstance();
        }
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.Builder, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.AppleOrBuilder> 
          getAppleFieldBuilder() {
        if (appleBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.getDefaultInstance();
          }
          appleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.Builder, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.AppleOrBuilder>(
                  (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return appleBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.Builder, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.PearOrBuilder> pearBuilder_;
      /**
       * <code>.Pear pear = 3;</code>
       */
      public boolean hasPear() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.Pear pear = 3;</code>
       */
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear getPear() {
        if (pearBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) dataBody_;
          }
          return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return pearBuilder_.getMessage();
          }
          return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.getDefaultInstance();
        }
      }
      /**
       * <code>.Pear pear = 3;</code>
       */
      public Builder setPear(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear value) {
        if (pearBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          pearBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Pear pear = 3;</code>
       */
      public Builder setPear(
          top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.Builder builderForValue) {
        if (pearBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          pearBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Pear pear = 3;</code>
       */
      public Builder mergePear(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear value) {
        if (pearBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.getDefaultInstance()) {
            dataBody_ = top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.newBuilder((top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            pearBuilder_.mergeFrom(value);
          }
          pearBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Pear pear = 3;</code>
       */
      public Builder clearPear() {
        if (pearBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          pearBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Pear pear = 3;</code>
       */
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.Builder getPearBuilder() {
        return getPearFieldBuilder().getBuilder();
      }
      /**
       * <code>.Pear pear = 3;</code>
       */
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.PearOrBuilder getPearOrBuilder() {
        if ((dataBodyCase_ == 3) && (pearBuilder_ != null)) {
          return pearBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) dataBody_;
          }
          return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.getDefaultInstance();
        }
      }
      /**
       * <code>.Pear pear = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.Builder, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.PearOrBuilder> 
          getPearFieldBuilder() {
        if (pearBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.getDefaultInstance();
          }
          pearBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.Builder, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.PearOrBuilder>(
                  (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return pearBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MyMessage)
    }

    // @@protoc_insertion_point(class_scope:MyMessage)
    private static final top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage();
    }

    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @java.lang.Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Apple)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *定义类的属性，int32是protoBuf定义的类型
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     * 1，2不是值！而是属性的顺序
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 1，2不是值！而是属性的顺序
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Apple}
   */
  public  static final class Apple extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Apple)
      AppleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Apple.newBuilder() to construct.
    private Apple(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Apple() {
      id_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Apple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_Apple_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_Apple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.class, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *定义类的属性，int32是protoBuf定义的类型
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 1，2不是值！而是属性的顺序
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 1，2不是值！而是属性的顺序
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple)) {
        return super.equals(obj);
      }
      top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple other = (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Apple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Apple)
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.AppleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_Apple_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_Apple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.class, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.Builder.class);
      }

      // Construct using top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_Apple_descriptor;
      }

      @java.lang.Override
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple getDefaultInstanceForType() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.getDefaultInstance();
      }

      @java.lang.Override
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple build() {
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple buildPartial() {
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple result = new top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) {
          return mergeFrom((top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple other) {
        if (other == top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       *定义类的属性，int32是protoBuf定义的类型
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *定义类的属性，int32是protoBuf定义的类型
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *定义类的属性，int32是protoBuf定义的类型
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 1，2不是值！而是属性的顺序
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 1，2不是值！而是属性的顺序
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 1，2不是值！而是属性的顺序
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1，2不是值！而是属性的顺序
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1，2不是值！而是属性的顺序
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Apple)
    }

    // @@protoc_insertion_point(class_scope:Apple)
    private static final top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple();
    }

    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Apple>
        PARSER = new com.google.protobuf.AbstractParser<Apple>() {
      @java.lang.Override
      public Apple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Apple(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Apple> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Apple> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Apple getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PearOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pear)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Pear}
   */
  public  static final class Pear extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Pear)
      PearOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pear.newBuilder() to construct.
    private Pear(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pear() {
      id_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Pear(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_Pear_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_Pear_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.class, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear)) {
        return super.equals(obj);
      }
      top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear other = (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Pear}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pear)
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.PearOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_Pear_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_Pear_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.class, top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.Builder.class);
      }

      // Construct using top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.internal_static_Pear_descriptor;
      }

      @java.lang.Override
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear getDefaultInstanceForType() {
        return top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.getDefaultInstance();
      }

      @java.lang.Override
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear build() {
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear buildPartial() {
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear result = new top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) {
          return mergeFrom((top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear other) {
        if (other == top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Pear)
    }

    // @@protoc_insertion_point(class_scope:Pear)
    private static final top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear();
    }

    public static top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pear>
        PARSER = new com.google.protobuf.AbstractParser<Pear>() {
      @java.lang.Override
      public Pear parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pear(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pear> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pear> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.zhaohaoren.netty.netty.protobuf.MyMessageProto.Pear getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Apple_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Apple_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pear_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pear_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MyMessage.proto\"\230\001\n\tMyMessage\022&\n\tdata_" +
      "type\030\001 \001(\0162\023.MyMessage.DataType\022\027\n\005apple" +
      "\030\002 \001(\0132\006.AppleH\000\022\025\n\004pear\030\003 \001(\0132\005.PearH\000\"" +
      "\'\n\010DataType\022\r\n\tAppleType\020\000\022\014\n\010PearType\020\001" +
      "B\n\n\010dataBody\"!\n\005Apple\022\n\n\002id\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\" \n\004Pear\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(" +
      "\tB7\n#top.zhaohaoren.netty.netty.protobuf" +
      "B\016MyMessageProtoH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyMessage_descriptor,
        new java.lang.String[] { "DataType", "Apple", "Pear", "DataBody", });
    internal_static_Apple_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Apple_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Apple_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_Pear_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Pear_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pear_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
